# Generated by Django 6.1.1 on 2026-09-06 22:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('tipo_ejercicio', models.CharField(max_length=100)),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id_gimnasio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gym', models.CharField(max_length=150)),
                ('ubicacion_gym', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Rutina')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', max_length=20, verbose_name='Nivel')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('FUNCIONARIO', 'Funcionario'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20, verbose_name='Rol de Usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id_detalle_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('orden_ejercicio', models.CharField(blank=True, max_length=50, null=True)),
                ('series_asignadas', models.IntegerField(default=0)),
                ('repeticiones_asignadas', models.IntegerField(default=0)),
                ('carga_asignada', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_descanso', models.CharField(blank=True, max_length=50, null=True)),
                ('lado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_rutina', to='gimnasioapp.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gimnasioapp.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('id_rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gimnasioapp.rutina')),
            ],
        ),
    ]
