# Generated by Django 6.1.1 on 2026-09-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioapp', '0002_remove_sesionentrenamiento_hora_fin_and_more'),
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='estado',
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_equipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_gimnasio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gimnasioapp.gimnasio'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(default='operativo', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maquina.equipo')),
            ],
        ),
    ]